### ISSUE TITLE
Talos bootstrap after provisioning the k8s cluster

### ISSUE THREAD

**Issue by kigsmtua** [siderolabs/cluster-api-control-plane-provider-talos#199]
``` 
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: cs-plane
spec:
  version: v1.30.0
  replicas: 1
  infrastructureTemplate:
    kind: VSphereMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: control-plane-template
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.7.6
      configPatches:
        - op: add
          path: /machine/network
          value:
            interfaces:
              - interface: eth0
                dhcp: true
                vip:
                  ip: 10.29.87.20
  ```
  
  I have provisioned the k8s cluster  using this config from the logs, I see that we still need to run a bootstrap command against the provided IP. The question is I have is  there a way to have bootstrap process automated, such that I don't need to manually run the bootstrap process
